import random
import simple_graphics as sg
import math

def draw_picture(width, height):
    draw_ocean(width, height)
    student_rendering(width, height)

    draw_bot(width, height)
    draw_top(width, height)
    
    

def draw_ocean_waves(num_waves, wave_thickness):
    canvas_width = int(sg._canvas['width'])
    canvas_height = int(sg._canvas['height'])
    
    colors = ["red", "green", "blue", "cyan", "magenta", "yellow"]
    sky_color = "white"
    dark_blue = "#006ccf"
    light_blue = "#a6e3f9"
    wave_step = canvas_width / max(1, num_waves)
    radius_main = wave_step * 0.5
    
    wave_base_y = canvas_height * 0.5
    
    for i in range(int(num_waves) + 1):
        x = i * wave_step

        sg.set_fill_color(dark_blue)
        sg.set_outline_color(dark_blue)
        sg.fill_circle(center_x=x, center_y=wave_base_y, radius=radius_main)
        
        sg.set_fill_color(light_blue)
        sg.set_outline_color(light_blue)
        sg.fill_circle(center_x=x - (radius_main * 0.15), center_y=wave_base_y - (radius_main * 0.25), radius=radius_main * 0.7)
        
        sg.set_fill_color(dark_blue)
        sg.set_outline_color(dark_blue)
        sg.fill_circle(center_x=x - (radius_main * 0.1), center_y=wave_base_y - (radius_main * 0.15), radius=radius_main * 0.65)

        sg.set_fill_color(sky_color)
        sg.set_outline_color(sky_color)
        sg.fill_circle(center_x=x + (radius_main * 0.85), center_y=wave_base_y - (radius_main * 0.1), radius=radius_main * 0.6)
        
        sg.set_fill_color(light_blue)
        sg.set_outline_color(light_blue)
        sg.fill_circle(center_x=x + (radius_main * 0.1), center_y=wave_base_y - (radius_main * 0.2), radius=3)
        sg.fill_circle(center_x=x + (radius_main * 0.3), center_y=wave_base_y - (radius_main * 0.45), radius=2)
        sg.fill_circle(center_x=x + (radius_main * 0.45), center_y=wave_base_y - (radius_main * 0.15), radius=3)
        
    sg.set_fill_color(dark_blue)
    sg.set_outline_color(dark_blue)
    sg.fill_rectangle(0, wave_base_y, canvas_width, wave_thickness)

    
def draw_ocean(width, height):
# SKY
    sky_height = height * 3/8

    sg.set_fill_color("skyblue")
    sg.fill_rectangle(0, 0, width, sky_height)

#OCEAN
    ocean_y = sky_height
    ocean_height = height - ocean_y

    sg.set_fill_color("deepskyblue")
    sg.fill_rectangle(0, ocean_y, width, ocean_height)

#SUN
    sun_radius = height / 4

    sun_center_x = width / 2
    sun_center_y = sky_height

    sg.set_fill_color("yellow")

#Draw top half of circle
    sg.fill_arc(
        sun_center_x - sun_radius,
        sun_center_y - sun_radius,
        sun_radius * 2,
        sun_radius * 2,
        0,
        180
    )

#CLOUDS
    
    sg.set_fill_color("white")

    #Cloud 1
    sg.fill_circle(120, 80, 25)
    sg.fill_circle(150, 70, 30)
    sg.fill_circle(180, 80, 25)

    #Cloud 2
    sg.fill_circle(420, 100, 20)
    sg.fill_circle(445, 90, 28)
    sg.fill_circle(475, 100, 20)

#BIRDS
    sg.set_outline_color("black")
    sg.set_line_thickness(2)

    #Bird 1
    sg.draw_line(250, 70, 260, 60)
    sg.draw_line(260, 60, 270, 70)

    #Bird 2
    sg.draw_line(320, 90, 330, 80)
    sg.draw_line(330, 80, 340, 90)

    #Bird 3
    sg.draw_line(500, 60, 510, 50)
    sg.draw_line(510, 50, 520, 60)
    
def draw_top(width, height):

    house_w = width * 0.50
    house_h = height * 0.25

    house_x = (width - house_w) / 2
    house_y = height * 0.42

    roof_height = height * 0.16

    roof_left_x = house_x - width * 0.03
    roof_left_y = house_y

    roof_peak_x = house_x + house_w / 2
    roof_peak_y = house_y - roof_height

    roof_right_x = house_x + house_w + width * 0.03
    roof_right_y = house_y

    # Roof
    sg.set_fill_color("#b22222")
    sg.set_outline_color("black")

    sg.fill_triangle(
        roof_left_x,
        roof_left_y,
        roof_peak_x,
        roof_peak_y,
        roof_right_x,
        roof_right_y
    )

    # Chimney
    chimney_w = house_w * 0.08
    chimney_h = roof_height * 0.8

    chimney_x = roof_peak_x + house_w * 0.18
    chimney_y = roof_peak_y + roof_height * 0.15

    sg.set_fill_color("#a52a2a")

    sg.fill_rectangle(
        chimney_x,
        chimney_y,
        chimney_w,
        chimney_h
    )

    # Chimney cap
    sg.set_fill_color("#7a1f1f")

    sg.fill_rectangle(
        chimney_x - chimney_w * 0.1,
        chimney_y - chimney_h * 0.08,
        chimney_w * 1.2,
        chimney_h * 0.08
    )

    # Smoke
    sg.set_fill_color("#dddddd")

    smoke_x = chimney_x + chimney_w/2

    for i in range(5):

        sg.fill_circle(
            smoke_x + (i % 2) * width * 0.01,
            chimney_y - height * (0.03 * (i + 1)),
            width * (0.015 + i * 0.003)
        )

"""
Draws the roof, chimney, and smoke for the house.

Attribution:
  - Generated by: OpenAI ChatGPT (GPT-4o)
  - Date: May 28th, 2026
  - Modifications: None. Used exactly as generated.
"""

"""
Draws the roof, chimney, and smoke for the house with modified layer positioning.

Attribution:
  - Created by: CheeseIsWeird
  - Date: May 28th, 2026
  - Modifications: Moved the chimney position so that it is layered/positioned in front of the roof.
"""
def draw_sand(y_position, height, num_dots=300):
    canvas_width = int(sg._canvas['width']) 
    sand_color = "#eab308"  # Yellow
    dot_color = "black"
    
    sg.set_fill_color(sand_color)
    sg.set_outline_color(sand_color)
    sg.fill_rectangle(0, y_position, canvas_width, height)
    
    sg.set_fill_color(dot_color)
    sg.set_outline_color(dot_color)
    
    for _ in range(num_dots):
        rand_x = random.randint(0, canvas_width)
        rand_y = random.randint(y_position, y_position + height)
        
        dot_radius = random.randint(1, 2)

        sg.fill_circle(center_x=rand_x, center_y=rand_y, radius=dot_radius)
def draw_bot(width, height):

    # House dimensions
    house_w = width * 0.50
    house_h = height * 0.25

    house_x = (width - house_w) / 2
    house_y = height * 0.42

    # Main house
    sg.set_fill_color("#d9d9d9")
    sg.set_outline_color("black")
    sg.fill_rectangle(
        house_x,
        house_y,
        house_w,
        house_h
    )

    # Door
    door_w = house_w * 0.18
    door_h = house_h * 0.65

    door_x = house_x + house_w/2 - door_w/2
    door_y = house_y + house_h - door_h

    sg.set_fill_color("#8b5a2b")
    sg.fill_rectangle(
        door_x,
        door_y,
        door_w,
        door_h
    )

    # Door knob
    sg.set_fill_color("gold")
    sg.fill_circle(
        door_x + door_w * 0.8,
        door_y + door_h * 0.5,
        width * 0.006
    )

    # Left window
    window_w = house_w * 0.18
    window_h = house_h * 0.25

    left_window_x = house_x + house_w * 0.12
    window_y = house_y + house_h * 0.25

    sg.set_fill_color("lightblue")
    sg.fill_rectangle(
        left_window_x,
        window_y,
        window_w,
        window_h
    )

    # Right window
    right_window_x = house_x + house_w * 0.70

    sg.fill_rectangle(
        right_window_x,
        window_y,
        window_w,
        window_h
    )

    # Window frames
    sg.set_outline_color("black")

    for wx in [left_window_x, right_window_x]:

        sg.draw_line(
            wx + window_w/2,
            window_y,
            wx + window_w/2,
            window_y + window_h
        )

        sg.draw_line(
            wx,
            window_y + window_h/2,
            wx + window_w,
            window_y + window_h/2
        )   

def student_rendering(width, height):

    draw_ocean_waves(
        num_waves=7,
        wave_thickness=int(height * 0.08)
    )

    sand_start_y = int(height * 0.63)
    sand_height = height - sand_start_y

    draw_sand(
        y_position=sand_start_y,
        height=sand_height,
        num_dots=400
    )


if __name__ == "__main__":
    sg.start(draw_picture, width = 800, height = 600)
